// 'use client'
import "./globals.css";
import Parent from "@/components/wrapper/Parent";

export const metadata = {
  title: "Goeasy Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Parent>
          {/* <div className="h-fit w-full pl-24 pr-28 pt-10 pb-10 "> */}
          <div className="h-fit w-full xl:pl-10 sm:pl-0 xl:pr-2 pt-10 pb-10 ">{children}</div>
        </Parent>
      </body>
    </html>
  );
}
