name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted   # This uses the Ubuntu environment provided by GitHub Actions
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      
  run: npm ci

    - name: Build Next.js app
      run: npm run build

    - run: |
          touch .env
          echo "${{ secrets.PROD }}" > .env
    - run: pm2 restart nextjs-app
