name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Replace with your target branch, if different (e.g., 'develop')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # Update to match the Node.js version you're using

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        KEY: ${{ secrets.EC2_KEY }}
        USER: ec2-user  # EC2 user (default is ec2-user for Amazon Linux)
      run: |
        scp -i $KEY -r . $USER@$HOST:/home/ec2-user/nextjs-app  # SCP the app to EC2 instance
        ssh -i $KEY $USER@$HOST << 'EOF'
          cd /home/ec2-user/nextjs-app
          npm install --production  # Install production dependencies on EC2
          pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start  # Start the app with PM2
        EOF
