name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest   # This uses the Ubuntu environment provided by GitHub Actions
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Check if the build already exists
    - name: Check if build exists
      id: check_build
      run: |
        if [ -d "./.next" ]; then
          echo "Build already exists"
          echo "build_exists=true" >> $GITHUB_ENV
        else
          echo "Build does not exist"
          echo "build_exists=false" >> $GITHUB_ENV

    # Only install dependencies and build if the build does not exist
    - name: Install dependencies
      if: env.build_exists == 'false'
      run: npm install

    - name: Build Next.js app
      if: env.build_exists == 'false'
      run: npm run build

    - name: Deploy to EC2
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: '.'
        target: '/home/ec2-user/nextjs-app'

    - name: SSH and Restart Application
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ec2-user/nextjs-app
          npm install --production
          pm2 restart nextjs-app || pm2 start npm --name "npm start" -- start

